#!/usr/bin/env bash
# pacioli deploy stage 3/4 — PERIMETER: nginx static front (:80, HTTP-only) + nftables contain.
#
# Runs ON the target host as root, after govern.sh. Staged/resumable.
# Extracted from the proven 2026-07-17 perimeter stage (run record:
# broker/docs/plans/2026-07-17-perimeter-stage.md), Debian seams pre-fixed:
#   - frappe's nginx template logs with format "main" that Debian's nginx.conf lacks
#   - deb13 homes are 0700 (provision already chmod o+x /home/frappe)
#   - reload races the apt-autostarted default config -> readback retries
#
# TLS is DELIBERATELY not terminated here: front :80 with the proxy of your house
# (Caddy, nginx, Traefik, HAProxy — any door). Set PROXY_IP so contain admits only it.
# The broker talks to :8000 by IP and never rides the proxy.
set -Eeuo pipefail
cd "$(dirname "$0")"
[ -f deploy.env ] || { echo "XX copy deploy.env.example -> deploy.env first"; exit 2; }
. ./deploy.env

exec > >(tee -a /root/pacioli-perimeter.log) 2>&1
STAGE=init; trap 'echo "### FAILED stage=[$STAGE] line=$LINENO rc=$?"' ERR
MARKS=/root/.pacioli-deploy-marks; mkdir -p "$MARKS"
mark(){ STAGE="$1"; echo "### STAGE $1 $(date -u +%H:%M:%S)"; }
done_mark(){ touch "$MARKS/$1"; }
skip(){ [ -f "$MARKS/$1" ] && { echo "### STAGE $1 already done — skip"; return 0; } || return 1; }

BENCH=/home/frappe/frappe-bench
SITE="$ERP_SITE"

# ---- p1: nginx static front ----
if ! skip p1-nginx; then mark p1-nginx
  su - frappe -c "cd $BENCH && source ~/.frappe_env && (bench setup nginx --yes || yes | bench setup nginx)"
  rm -f /etc/nginx/sites-enabled/default
  cat >/etc/nginx/conf.d/00-log-format.conf <<'LOGFMT'
log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                '$status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for"';
LOGFMT
  ln -sf $BENCH/config/nginx.conf /etc/nginx/conf.d/frappe-bench.conf
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
  code=000
  for i in 1 2 3 4 5; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 -H "Host: $SITE" http://127.0.0.1:80/api/method/ping)
    [ "$code" = "200" ] && break; sleep 2
  done
  [ "$code" = "200" ] || { echo "XX nginx front readback: $code"; exit 1; }
  # prove the STATIC path — the thing nginx is for (assets are symlinks: find -L; and
  # -print -quit, never "| head" — SIGPIPE under pipefail kills the script silently)
  asset=$(cd $BENCH/sites/assets && find -L . -maxdepth 5 -type f \( -name '*.svg' -o -name '*.css' -o -name '*.js' \) -print -quit 2>/dev/null | sed 's|^\./||')
  [ -n "$asset" ] || { echo "XX no asset found to probe"; exit 1; }
  acode=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 -H "Host: $SITE" "http://127.0.0.1:80/assets/$asset")
  [ "$acode" = "200" ] || { echo "XX static asset readback: $acode for /assets/$asset"; exit 1; }
  echo "ok NGINX_FRONT (:80 API + /assets both 200 for Host $SITE)"
  done_mark p1-nginx
fi

# ---- p2: contain (nftables IN the host; blast radius = this box) ----
if ! skip p2-contain; then mark p2-contain
  if [ -z "${BROKER_HOST_IP:-}" ]; then
    echo "!! BROKER_HOST_IP empty — skipping contain (perimeter is nginx-only). Set it and rerun to contain."
  else
    apt-get install -y nftables >/dev/null
    {
      echo '#!/usr/sbin/nft -f'
      echo "# $SITE inbound containment — generated by pacioli deploy $(date -u +%F)"
      echo 'flush ruleset'
      echo 'table inet filter {'
      echo '  chain input {'
      echo '    type filter hook input priority 0; policy drop;'
      echo '    ct state established,related accept'
      echo '    ct state invalid drop'
      echo '    iif "lo" accept'
      echo '    ip protocol icmp accept'
      echo '    meta l4proto ipv6-icmp accept'
      [ -n "${PROXY_IP:-}" ] && echo "    ip saddr $PROXY_IP tcp dport 80 accept"
      echo "    ip saddr $BROKER_HOST_IP tcp dport { 8000, 9000, 22 } accept"
      for ip in ${ADMIN_SSH_IPS:-}; do echo "    ip saddr $ip tcp dport 22 accept"; done
      echo '  }'
      echo '  chain forward { type filter hook forward priority 0; policy drop; }'
      echo '  chain output  { type filter hook output  priority 0; policy accept; }'
      echo '}'
    } >/etc/nftables.conf
    nft -c -f /etc/nftables.conf
    systemctl enable --now nftables
    systemctl restart nftables
    # readback via capture, NEVER `| grep -q` — grep -q closing the pipe SIGPIPEs the
    # producer (exit 141), and under pipefail a successful match reads as failure. The
    # same landmine as `find | head`; the lab proof caught it twice before it was named.
    okfw=""
    for i in 1 2 3 4 5; do
      rs=$(nft list ruleset 2>/dev/null || true)
      case "$rs" in *"policy drop"*) okfw=1; break;; esac
      sleep 1
    done
    [ -n "$okfw" ] || { echo "XX ruleset readback empty after 5s"; exit 1; }
    echo "ok CONTAIN_LIVE — UNDO: systemctl disable --now nftables && nft flush ruleset"
  fi
  done_mark p2-contain
fi

echo "### PERIMETER_DONE $(date -u) — point your TLS proxy at this host:80 for $SITE; broker stays by-IP :8000"
